src/Entity/Country.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CountryRepository")
 */
class Country
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Stat", mappedBy="country", orphanRemoval=true)
     */
    private $stats;

    public function __construct()
    {
        $this->stats = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Stat[]
     */
    public function getStats(): Collection
    {
        return $this->stats;
    }

    public function addStat(Stat $stat): self
    {
        if (!$this->stats->contains($stat)) {
            $this->stats[] = $stat;
            $stat->setCountry($this);
        }

        return $this;
    }

    public function removeStat(Stat $stat): self
    {
        if ($this->stats->contains($stat)) {
            $this->stats->removeElement($stat);
            // set the owning side to null (unless already changed)
            if ($stat->getCountry() === $this) {
                $stat->setCountry(null);
            }
        }

        return $this;
    }

    public function getHealed(){
        $total = 0;
        foreach ($this->getStats() as $stat){
            $total += $stat->getHealed();
        }
        return $total;
    }

    public function getContaminated(){
        $total = 0;
        foreach ($this->getStats() as $stat){
            $total += $stat->getContaminated();
        }
        return $total;
    }

    public function getZombified(){
        $total = 0;
        foreach ($this->getStats() as $stat){
            $total += $stat->getZombified();
        }
        return $total;
    }
}

src/Entity/Stat.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StatRepository")
 */
class Stat
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $contaminated;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $healed;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $zombified;

    /**
     * @ORM\Column(type="date")
     */
    private $stat_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Country", inversedBy="stats")
     * @ORM\JoinColumn(nullable=false)
     */
    private $country;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContaminated(): ?int
    {
        return $this->contaminated;
    }

    public function setContaminated(?int $contaminated): self
    {
        $this->contaminated = $contaminated;

        return $this;
    }

    public function getHealed(): ?int
    {
        return $this->healed;
    }

    public function setHealed(?int $healed): self
    {
        $this->healed = $healed;

        return $this;
    }

    public function getZombified(): ?int
    {
        return $this->zombified;
    }

    public function setZombified(?int $zombified): self
    {
        $this->zombified = $zombified;

        return $this;
    }

    public function getStatDate(): ?\DateTimeInterface
    {
        return $this->stat_date;
    }

    public function setStatDate(\DateTimeInterface $stat_date): self
    {
        $this->stat_date = $stat_date;

        return $this;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): self
    {
        $this->country = $country;

        return $this;
    }
}

src/Form/CountryType.php
<?php

namespace App\Form;

use App\Entity\Country;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CountryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Country::class,
        ]);
    }
}

src/Controller/CountryController.php
<?php

namespace App\Controller;

use App\Entity\Country;
use App\Form\CountryType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CountryController extends AbstractController
{
    /**
     * @Route("/country", name="country")
     */
    public function index()
    {
        return $this->render('country/index.html.twig', [
            'controller_name' => 'CountryController',
        ]);
    }

    /**
    * Affiche le formulaire de création d'une country'
    * @Route("/country/new", name="country_new", methods={"GET", "POST"})
    */
    public function new(Request $request) {
    $country = new Country();

    $form = $this->createForm(CountryType::class, $country);

    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $country = $form->getData();

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($country);
        $entityManager->flush();

        return $this->redirectToRoute('app_index');
    }

    return $this->render('country/form.html.twig', [
        'form' => $form->createView()
    ]);
}

    /**
     * @Route("/country/{country}", name="country_show", methods={"GET"}, requirements={"country"="\d+"})
     */
    public function show(Country $country): Response
    {
        return $this->render('country/show.html.twig', [
            'country' => $country
        ]);
    }
}

templates/country/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un pays{% endblock %}

{% block body %}

    {{ form_start(form) }}
    {{ form_widget(form) }}
        <button class="btn btn-success">Ajouter un pays</button>
    {{ form_end(form) }}

{% endblock %}

templates/country/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CountryController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/Rijuu/Desktop/HUMAN BOOSTER/Code/symfo/examSymfo/src/Controller/CountryController.php'|file_link(0) }}">src/Controller/CountryController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/Rijuu/Desktop/HUMAN BOOSTER/Code/symfo/examSymfo/templates/country/index.html.twig'|file_link(0) }}">templates/country/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/country/show.html.twig
{% extends "base.html.twig" %}

{% block title %}Informations{% endblock %}

{% block body %}

<h1 class="text-center my-3">Informations du pays : {{ country.name }}</h1>

<table class="table mt-5">
    <thead>
        <tr>
            <th class="text-center">Contaminé</th>
            <th class="text-center">Soigné</th>
            <th class="text-center">Zombifié</th>
            <th class="text-center">Date d'entrée</th>
        </tr>
    </thead>
    <tbody>
        {% for stat in country.stats %}
        <tr>
            <td class="text-center">{{ stat.contaminated }}</td>
            {% if stat.healed > stat.zombified %}
            <td class="text-center" style="background-color: rgb(16, 202, 16);">{{ stat.healed }}</td>
            {% else %}
            <td class="text-center" style="background-color: rgb(255, 38, 38);">{{ stat.healed }}</td>
            {% endif %}
            <td class="text-center">{{ stat.zombified }}</td>
            <td class="text-center">{{ stat.statDate | date("m/d/Y") }}</td>
        </tr>
        {% else %}
        <tr>
            <td class="text-center"><b>Pas de donnée pour ce pays pour le moment</b></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock body %}